# The name of this file starts from the underscore to load it before any other file from the same directory.
# If it's not loaded first, services from issue-tracker-specific configuration files
# might be autowired with wrong dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    microsoft.oauth.client_id: '%env(MICROSOFT_OAUTH_CLIENT_ID)%'
    microsoft.oauth.tenant_id: '%env(MICROSOFT_OAUTH_TENANT_ID)%'
    microsoft.oauth.public_keys_url: '%env(MICROSOFT_OAUTH_PUBLIC_KEYS_URL)%'
    mercure.jwt_secret: '%env(MERCURE_JWT_SECRET)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $commonHost: '%env(COMMON_HOST)%'
            Symfony\Component\Serializer\Mapping\Factory\ClassMetadataFactoryInterface: '@app.integration.serializer.class_metadata_factory'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../../src/'
        exclude:
            - '../../src/DependencyInjection/'
            - '../../src/Entity/'
            - '../../src/Kernel.php'
            - '../../src/Tests/'
            # Exclude VersionOne-specific classes defined in another file
            - '../../src/Integration/VersionOne/'
            - '../../src/Maker/MakeVersionOneAssetMetadata.php'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../../src/Controller/'
        tags: ['controller.service_arguments']

    App\DataPersister\WorkitemPersisterDecorator:
        decorates: 'api_platform.doctrine.orm.data_persister'

    App\Entity\Listener\AbstractEntityListener:
        tags:
            -   name: doctrine.orm.entity_listener
                event: postLoad
                entity: App\Entity\Epic
            -   name: doctrine.orm.entity_listener
                event: postLoad
                entity: App\Entity\Workitem

    App\Entity\Listener\ProjectSettingsEntityListener:
        tags:
            -   name: doctrine.orm.entity_listener
                event: preRemove
                method: preRemove
                entity: App\Entity\ProjectSettings

    App\Integration\AssetExporterInterface: '@app.integration.asset_exporter'

    App\Integration\AssetExternalUrlProviderInterface: '@app.integration.asset_external_url_provider'

    app.integration.serializer.class_metadata_factory:
        class: Symfony\Component\Serializer\Mapping\Factory\ClassMetadataFactory
        arguments: ['@app.integration.serializer.yaml_loader']

    app.integration.serializer.yaml_loader:
        class: Symfony\Component\Serializer\Mapping\Loader\YamlFileLoader
        arguments: ['%app.integration.serializer.class_metadata%']

    App\Mercure\JWTProvider:
        arguments: ['%mercure.jwt_secret%']

    App\Security\AbstractJWTAuthenticator:
        abstract: true
        autowire: true
        arguments:
            Jose\Component\Core\JWKSet: '@jose.key_set.microsoft'

    App\Security\CookieJWTAuthenticator:
        autowire: true
        autoconfigure: false
        parent: App\Security\AbstractJWTAuthenticator

    App\Security\HeaderJWTAuthenticator:
        autowire: true
        autoconfigure: false

        parent: App\Security\AbstractJWTAuthenticator

    App\ServerSentEvent\EstimateChangesListener:
        tags:
            -   name: doctrine.event_listener
                event: onFlush

    Symfony\Component\Serializer\Mapping\ClassDiscriminatorResolverInterface:
        class: Symfony\Component\Serializer\Mapping\ClassDiscriminatorFromClassMetadata
