version: '3.4'

x-react-app-env-vars: &react-app-env-vars
  REACT_APP_API_ENTRYPOINT: ${API_ENTRYPOINT:?}
  REACT_APP_MICROSOFT_OAUTH_CLIENT_ID: ${MICROSOFT_OAUTH_CLIENT_ID:?}
  REACT_APP_MICROSOFT_OAUTH_TENANT_ENDPOINT: ${MICROSOFT_OAUTH_TENANT_ENDPOINT:?}

services:
  api:
    build:
      context: ./api
      target: ${PHP_IMAGE_TARGET:?}
      cache_from:
        - ${PHP_IMAGE:?}
      args:
        DATABASE_URL: ${DATABASE_URL:?}
        ROUTER_REQUEST_CONTEXT_SCHEME: ${ROUTER_REQUEST_CONTEXT_SCHEME:?}
        API_HOST: ${API_HOST:?}

  client:
    build:
      context: ./client
      target: ${CLIENT_IMAGE_TARGET:?}
      args: *react-app-env-vars
      cache_from:
        - ${CLIENT_IMAGE:?}

  admin:
    build:
      context: ./admin
      target: ${ADMIN_IMAGE_TARGET:?}
      args: *react-app-env-vars
      cache_from:
        - ${ADMIN_IMAGE:?}

volumes:
  db-data:
