version: '3.4'

services:
  api:
    image: ${PHP_IMAGE:?}
    environment:
      APP_ENV: ${APP_ENV:?}
      APP_DEBUG: ${APP_DEBUG:?}
      APP_SECRET: ${APP_SECRET:?}
      CORS_ALLOW_ORIGIN: ${CORS_ALLOW_ORIGIN:?}
      TRUSTED_HOSTS: ${TRUSTED_HOSTS:?}
      TRUSTED_PROXIES: ${TRUSTED_PROXIES:-10.0.0.0/8,172.16.0.0/12,192.168.0.0/16}
      DATABASE_URL: ${DATABASE_URL:?}
      ROUTER_REQUEST_CONTEXT_SCHEME: ${ROUTER_REQUEST_CONTEXT_SCHEME:?}
      API_HOST: ${API_HOST:?}
      COMMON_HOST: ${CLIENT_HOST}
      MESSENGER_TRANSPORT_DSN: ${MESSENGER_TRANSPORT_DSN:?}
      MERCURE_JWT_SECRET: ${MERCURE_JWT_KEY:?}
      MERCURE_PUBLISH_URL: ${MERCURE_PUBLISH_URL:?}
      MERCURE_SUBSCRIBE_URL: ${MERCURE_SUBSCRIBE_URL:?}
      VERSION_ONE_ACCESS_TOKEN: ${VERSION_ONE_ACCESS_TOKEN:?}
      # Example: https://www2.v1host.com/CompanyName
      VERSION_ONE_SERVER_BASE_URI: ${VERSION_ONE_SERVER_BASE_URI:?}
      MICROSOFT_OAUTH_CLIENT_ID: ${MICROSOFT_OAUTH_CLIENT_ID:?}
      MICROSOFT_OAUTH_TENANT_ID: ${MICROSOFT_OAUTH_TENANT_ID:?}
      MICROSOFT_OAUTH_PUBLIC_KEYS_URL: ${MICROSOFT_OAUTH_PUBLIC_KEYS_URL:?}
      VIRTUAL_HOST: ${API_HOST:?}
      VIRTUAL_PROTO: fastcgi
      VIRTUAL_ROOT: /srv/api/public
    depends_on:
      - db
    volumes:
    - vhostd:/etc/nginx/vhost.d

  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: ${DB_NAME:?}
      POSTGRES_USER: ${DB_USER:?}
      POSTGRES_PASSWORD: ${DB_PASSWORD:?}
    volumes:
      - db-data:/var/lib/postgresql/data:rw

  mercure:
    image: dunglas/mercure
    environment:
      CORS_ALLOWED_ORIGINS: ${MERCURE_CORS_ALLOWED_ORIGINS:?}
      JWT_KEY: ${MERCURE_JWT_KEY:?}
      VIRTUAL_HOST: ${MERCURE_HOST:?}

  client:
    image: ${CLIENT_IMAGE:?}
    environment:
      VIRTUAL_HOST: ${CLIENT_HOST:?}

  admin:
    image: ${ADMIN_IMAGE:?}
    environment:
      VIRTUAL_HOST: ${ADMIN_HOST:?}
    
  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - certs:/etc/nginx/certs
      - vhostd:/etc/nginx/vhost.d:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - api

volumes:
  db-data:
  certs:
  vhostd:
