version: '3.4'

x-react-app-env-vars: &react-app-env-vars
  REACT_APP_API_ENTRYPOINT: ${API_ENTRYPOINT:?}
  REACT_APP_MICROSOFT_OAUTH_CLIENT_ID: ${MICROSOFT_OAUTH_CLIENT_ID:?}
  REACT_APP_MICROSOFT_OAUTH_TENANT_ENDPOINT: ${MICROSOFT_OAUTH_TENANT_ENDPOINT:?}

x-api-build-cache-from: &api-build-cache-from
  cache_from:
    - ${NGINX_IMAGE:?}
    - ${PHP_IMAGE:?}
    - ${VARNISH_IMAGE:?}

x-api-build-args: &api-build-args
  args:
    DATABASE_URL: ${DATABASE_URL:?}
    ROUTER_REQUEST_CONTEXT_SCHEME: ${ROUTER_REQUEST_CONTEXT_SCHEME:?}
    ROUTER_REQUEST_CONTEXT_HOST: ${ROUTER_REQUEST_CONTEXT_HOST:?}

services:
  php:
    build:
      context: ./api
      target: ${PHP_IMAGE_TARGET:?}
      <<: *api-build-args
      <<: *api-build-cache-from

  api:
    build:
      context: ./api
      target: api_platform_nginx
      <<: *api-build-args
      <<: *api-build-cache-from

  cache-proxy:
    build:
      context: ./api
      target: api_platform_varnish
      <<: *api-build-args
      <<: *api-build-cache-from

  client:
    build:
      context: ./client
      target: ${CLIENT_IMAGE_TARGET:?}
      args: *react-app-env-vars
      cache_from:
        - ${CLIENT_IMAGE:?}

  admin:
    build:
      context: ./admin
      target: ${ADMIN_IMAGE_TARGET:?}
      args: *react-app-env-vars
      cache_from:
        - ${ADMIN_IMAGE:?}

volumes:
  db-data:
