version: '3.4'

services:
  api:
    restart: always
    environment:
      LETSENCRYPT_HOST: ${API_HOST:?}

  client:
    restart: always
    environment:
      LETSENCRYPT_HOST: ${CLIENT_HOST:?}

  admin:
    restart: always
    environment:
      LETSENCRYPT_HOST: ${ADMIN_HOST:?}

  db:
    restart: always

  mercure:
    restart: always
    environment:
      LETSENCRYPT_HOST: ${MERCURE_HOST:?}

  nginx-proxy:
    restart: always
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    volumes:
      - html:/usr/share/nginx/html:ro

  letsencrypt:
    restart: always
    image: jrcs/letsencrypt-nginx-proxy-companion
    environment:
      DEFAULT_EMAIL: ${LETSENCRYPT_EMAIL:?}
    depends_on:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhostd:/etc/nginx/vhost.d
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  html:

