version: '3.4'

x-react-app-env-vars: &react-app-env-vars
  REACT_APP_API_ENTRYPOINT: ${API_ENTRYPOINT:?}
  REACT_APP_MICROSOFT_OAUTH_CLIENT_ID: ${MICROSOFT_OAUTH_CLIENT_ID:?}
  REACT_APP_MICROSOFT_OAUTH_TENANT_ENDPOINT: ${MICROSOFT_OAUTH_TENANT_ENDPOINT:?}

services:
  api:
    environment:
      XDEBUG_CONFIG: >-
        remote_enable=1
        remote_host=host.docker.internal
      PHP_IDE_CONFIG: serverName=api-platform
    volumes:
      - ./api:/srv/api:rw,cached
      - ./api/docker/nginx/vhost.d/_location.dist:/etc/nginx/vhost.d/_location.dist
      - ./api/docker/php/conf.d/api-platform.dev.ini:/usr/local/etc/php/conf.d/api-platform.ini
      - ./api/docker/php/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint
      - certs:/certs:ro,nocopy
    depends_on:
      - dev-tls

  db:
    ports:
      - 5432:5432

  admin:
    environment:
      <<: *react-app-env-vars
    volumes:
      - ./admin:/usr/src/admin:rw,cached
      - certs:/usr/src/admin/node_modules/webpack-dev-server/ssl:ro,nocopy
    tty: true # https://github.com/facebook/create-react-app/issues/8688

  client:
    environment:
      <<: *react-app-env-vars
      API_PLATFORM_CLIENT_GENERATOR_ENTRYPOINT: http://api
      API_PLATFORM_CLIENT_GENERATOR_OUTPUT: src
    volumes:
      - ./client:/usr/src/client:rw,cached
      - certs:/usr/src/client/node_modules/webpack-dev-server/ssl:ro,nocopy
    tty: true # https://github.com/facebook/create-react-app/issues/8688

  nginx-proxy:
    depends_on:
      - dev-tls

  dev-tls:
    build:
      context: ./docker/dev-tls
      args:
        COMMON_HOST: ${COMMON_HOST:?}
    volumes:
      - certs:/certs:rw
