version: '3.4'

x-react-app-env-vars: &react-app-env-vars
  REACT_APP_API_ENTRYPOINT: ${API_SCHEME:?}://${API_HOST:?}
  REACT_APP_MICROSOFT_OAUTH_CLIENT_ID: ${MICROSOFT_OAUTH_CLIENT_ID:?}
  REACT_APP_MICROSOFT_OAUTH_TENANT_ENDPOINT: ${MICROSOFT_OAUTH_TENANT_ENDPOINT:?}

services:
  api:
    build:
      context: ./api
      target: ${PHP_IMAGE_TARGET:?}
      args:
        DATABASE_URL: ${DATABASE_URL:?}
        API_HOST: ${API_HOST:?}
        API_SCHEME: ${API_SCHEME:?}

  client:
    build:
      context: ./client
      target: ${CLIENT_IMAGE_TARGET:?}
      args: 
        <<: *react-app-env-vars
        REACT_APP_ADMIN_URL: ${ADMIN_URL:?}

  admin:
    build:
      context: ./admin
      target: ${ADMIN_IMAGE_TARGET:?}
      args: *react-app-env-vars

volumes:
  db-data:
