version: '3.4'

services:
  php:
    image: ${PHP_IMAGE:?}
    environment:
      APP_ENV: ${APP_ENV:?}
      APP_DEBUG: ${APP_DEBUG:?}
      APP_SECRET: ${APP_SECRET:?}
      CORS_ALLOW_ORIGIN: ${CORS_ALLOW_ORIGIN:?}
      TRUSTED_HOSTS: ${TRUSTED_HOSTS:?}
      TRUSTED_PROXIES: ${TRUSTED_PROXIES:-10.0.0.0/8,172.16.0.0/12,192.168.0.0/16}
      DATABASE_URL: ${DATABASE_URL:?}
      ROUTER_REQUEST_CONTEXT_SCHEME: ${ROUTER_REQUEST_CONTEXT_SCHEME:?}
      ROUTER_REQUEST_CONTEXT_HOST: ${ROUTER_REQUEST_CONTEXT_HOST:?}
      MESSENGER_TRANSPORT_DSN: ${MESSENGER_TRANSPORT_DSN:?}
      MERCURE_JWT_TOKEN: ${MERCURE_JWT_TOKEN:?}
      MERCURE_PUBLISH_URL: https://mercure/.well-known/mercure
      MERCURE_SUBSCRIBE_URL: ${MERCURE_SUBSCRIBE_URL:?}
      VERSION_ONE_ACCESS_TOKEN: ${VERSION_ONE_ACCESS_TOKEN:?}
      # Example: https://www2.v1host.com/CompanyName
      VERSION_ONE_SERVER_BASE_URI: ${VERSION_ONE_SERVER_BASE_URI:?}
      MICROSOFT_OAUTH_CLIENT_ID: ${MICROSOFT_OAUTH_CLIENT_ID:?}
      MICROSOFT_OAUTH_TENANT_ID: ${MICROSOFT_OAUTH_TENANT_ID:?}
      MICROSOFT_OAUTH_PUBLIC_KEYS_URL: ${MICROSOFT_OAUTH_PUBLIC_KEYS_URL:?}
    depends_on:
      - db

  api:
    image: ${NGINX_IMAGE:?}
    depends_on:
      - php

  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: ${DB_NAME:?}
      POSTGRES_USER: ${DB_USER:?}
      POSTGRES_PASSWORD: ${DB_PASSWORD:?}
    volumes:
      - db-data:/var/lib/postgresql/data:rw

  mercure:
    image: dunglas/mercure
    environment:
      ALLOW_ANONYMOUS: ${MERCURE_ALLOW_ANONYMOUS:?}
      CORS_ALLOWED_ORIGINS: ${MERCURE_CORS_ALLOWED_ORIGINS:?}
      JWT_KEY: ${MERCURE_JWT_KEY:?}

  client:
    image: ${CLIENT_IMAGE:?}

  admin:
    image: ${ADMIN_IMAGE:?}

volumes:
  db-data:
