doctrine:
    dbal:
        # The serverVersion param must be specified in the DATABASE_URL
        url: '%env(DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
        dql:
            string_functions:
                GET_JSON_FIELD: \Opsway\Doctrine\ORM\Query\AST\Functions\GetJsonField
                JSON_ARRAY_ELEM: App\ORM\Query\Functions\JsonArrayElements
