httplug:
    plugins:
        retry:
            retry: 1
        cache:
            cache_pool: cache.app
            config:
                default_ttl: 1800

    discovery:
        client: auto

    clients:
        app:
            http_methods_client: true
            plugins:
                - httplug.plugin.content_length
                - httplug.plugin.redirect
        jwt_authenticator:
            factory: httplug.factory.auto
            plugins: 
                - httplug.plugin.cache
        version_one:
            plugins:
                - authentication:
                      bearer: 
                          type: bearer
                          token: '%version_one.access_token%'
                - base_uri:
                      uri: '%version_one.server_base_uri%'
                - header_set:
                      headers:
                          Accept: application/json
                          Content-Type: application/json
