nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['%env(ADMIN_URL)%', '%env(CLIENT_URL)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization', 'Preload', 'Fields']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/': null
