security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        users_in_memory: { memory: null }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        webhooks_jira:
            pattern: ^/webhooks/jira/
            security: false
        main:
            logout:
                path: logout
                success_handler: App\Security\LogoutSuccessHandler 
            stateless: true
            guard:
                authenticators:
                    - App\Security\CookieJWTAuthenticator
                    - App\Security\HeaderJWTAuthenticator
                entry_point: App\Security\CookieJWTAuthenticator
