export const ADMIN_URL = process.env.REACT_APP_ADMIN_URL;
export const API_ENTRYPOINT = process.env.REACT_APP_API_ENTRYPOINT;
export const MICROSOFT_OAUTH_CLIENT_ID = process.env.REACT_APP_MICROSOFT_OAUTH_CLIENT_ID;
export const MICROSOFT_OAUTH_TENANT_ENDPOINT = process.env.REACT_APP_MICROSOFT_OAUTH_TENANT_ENDPOINT;
