# This file is the entry point to configure your own services.
imports:
    # https://symfony.com/doc/current/service_container/import.html#importing-configuration-with-imports
    - { resource: services/ }
