# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    version_one.access_token: '%env(VERSION_ONE_ACCESS_TOKEN)%'
    version_one.server_base_uri: '%env(VERSION_ONE_SERVER_BASE_URI)%'
    version_one.endpoint.bulk: '/api/asset'
    version_one.endpoint.asset_detail: '/assetdetail.v1'
    version_one.filter.epic.status_name: 'Parking Lot'
    microsoft.oauth.client_id: '%env(MICROSOFT_OAUTH_CLIENT_ID)%'
    microsoft.oauth.tenant_id: '%env(MICROSOFT_OAUTH_TENANT_ID)%'
    microsoft.oauth.public_keys_url: '%env(MICROSOFT_OAUTH_PUBLIC_KEYS_URL)%'
    mercure.jwt_secret: '%env(MERCURE_JWT_SECRET)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $commonHost: '%env(COMMON_HOST)%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\VersionOne\BulkApiClient:
        arguments:
            Psr\Http\Client\ClientInterface: '@httplug.client.version_one'
            $bulkEndpoint: '%version_one.endpoint.bulk%'

    App\Entity\Listener\AbstractEntityListener:
        tags:
            - name: doctrine.orm.entity_listener
              event: postLoad
              entity: App\Entity\AbstractEntity
            - name: doctrine.orm.entity_listener
              event: preUpdate
              entity: App\Entity\AbstractEntity

    App\Entity\Listener\ProgramIncrementEntityListener:
        tags:
            - name: doctrine.orm.entity_listener
              event: postPersist
              method: importEntities
              entity: App\Entity\ProgramIncrement
            - name: doctrine.orm.entity_listener
              event: postUpdate
              method: importEntities
              entity: App\Entity\ProgramIncrement

    App\ServerSentEvent\EstimateChangesListener:
        tags:
            - name: doctrine.event_listener
              event: onFlush

    App\Security\AbstractJWTAuthenticator:
        abstract: true
        autowire: true
        arguments:
            Jose\Component\Core\JWKSet: '@jose.key_set.microsoft'

    App\Security\CookieJWTAuthenticator:
        autowire: true
        autoconfigure: false
        parent: App\Security\AbstractJWTAuthenticator

    App\Security\HeaderJWTAuthenticator:
        autowire: true
        autoconfigure: false
        parent: App\Security\AbstractJWTAuthenticator

    App\Mercure\JWTProvider:
        arguments: ['%mercure.jwt_secret%']
