# TODO: Find out the best way to share common properties (use discriminator?)
App\Entity\BacklogGroup:
    attributes:
        externalId:
            serialized_name: ID
        name:
            serialized_name: Name
        changedAt:
            serialized_name: ChangeDateUTC
        isDeleted:
            serialized_name: IsDeleted
        project:
            serialized_name: Scope

App\Entity\Epic:
    attributes:
        externalId:
            serialized_name: ID
        name:
            serialized_name: Name
        changedAt:
            serialized_name: ChangeDateUTC
        isDeleted:
            serialized_name: IsDeleted
        project:
            serialized_name: Scope
        status:
            serialized_name: Status
        wsjf:
            serialized_name: Wsjf

App\Entity\EpicStatus:
    attributes:
        externalId:
            serialized_name: ID
        name:
            serialized_name: Name
        changedAt:
            serialized_name: ChangeDateUTC
        isDeleted:
            serialized_name: IsDeleted

App\Entity\Project:
    attributes:
        externalId:
            serialized_name: ID
        name:
            serialized_name: Name
        changedAt:
            serialized_name: ChangeDateUTC
        isDeleted:
            serialized_name: IsDeleted
        sprintSchedule:
            serialized_name: Schedule

App\Entity\Sprint:
    attributes:
        externalId:
            serialized_name: ID
        name:
            serialized_name: Name
        changedAt:
            serialized_name: ChangeDateUTC
        isDeleted:
            serialized_name: IsDeleted
        schedule:
            serialized_name: Schedule
        startDate:
            serialized_name: BeginDate
        endDate:
            serialized_name: EndDate

App\Entity\SprintSchedule:
    attributes:
        externalId:
            serialized_name: ID
        name:
            serialized_name: Name
        changedAt:
            serialized_name: ChangeDateUTC
        isDeleted:
            serialized_name: IsDeleted

App\Entity\Team:
    attributes:
        externalId:
            serialized_name: ID
        name:
            serialized_name: Name
        changedAt:
            serialized_name: ChangeDateUTC
        isDeleted:
            serialized_name: IsDeleted

App\Entity\Workitem:
    attributes:
        externalId:
            serialized_name: ID
        name:
            serialized_name: Name
        changedAt:
            serialized_name: ChangeDateUTC
        isDeleted:
            serialized_name: IsDeleted
        backlogGroup:
            serialized_name: Parent
        epic:
            serialized_name: Super
        project:
            serialized_name: Scope
        sprint:
            serialized_name: Timebox
        team:
            serialized_name: Team
